//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hetman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KomendaPolicjiDBEntities : DbContext
    {
        public KomendaPolicjiDBEntities()
            : base("name=KomendaPolicjiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pojazdy> Pojazdies { get; set; }
        public virtual DbSet<Policjanci> Policjancis { get; set; }
        public virtual DbSet<Sprzet> Sprzets { get; set; }
        public virtual DbSet<Zgloszenia> Zgloszenias { get; set; }
    }
}
