//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hetman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazdy
    {
        public int Id_pojazdu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Rok_produkcji { get; set; }
    }
}
