//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hetman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzet
    {
        public int ID_sprzetu { get; set; }
        public string Nazwa { get; set; }
        public double wartosc { get; set; }

 
    }
}
