//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hetman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgloszenia
    {
        public int Id_Zgloszenia { get; set; }
        public string Nazwa { get; set; }
        public string Imie_zglaszajacego { get; set; }
        public string Nazwisko_zglaszajacego { get; set; }
        public int Telefon_zglaszajacego { get; set; }
        public string Opis_zdarzenia { get; set; }
    }
}
